services:
  web:
    volumes:
      - '../../../app:/opt/node_app/app'
      - '../../../lib:/opt/node_app/lib'
      - '../../../views:/opt/node_app/views'
      - '../../../public:/opt/node_app/public'
      - '../../../extensions:/opt/node_app/extensions'
      - '../../../db:/opt/node_app/db'
      - '../../../certs:/opt/node_app/certs'
    ports:
      - '8100:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Development/web/Dockerfile'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    depends_on:
      - 'db'
      - 'redis'
  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'v4yB67Xl'
      MYSQL_DATABASE: 'scriptassist-build'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'H1e6WAwc'
    volumes:
      - './db_init:/docker-entrypoint-initdb.d'
    ports:
      - '9906:3306'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
  redis:
    image: 'redis:alpine'
    hostname: 'redis'
    restart: 'always'
    volumes:
      - 'redis-volume:/data'
volumes:
  redis-volume: ~
